### ISSUE TITLE
python.exe和.NET Framework 2.0 SDK这都是啥啊

### ISSUE THREAD

**Issue by ZhangWren** [angular-programming/angular-questionnaire#1]
python.exe和.NET Framework 2.0 SDK这都是啥啊，很无语诶，为什么会用到这些？这很容易让人头大啊

**Comment by ghost** [comment]
angular应用本身并不会依赖 python 和 .NET Framework 2.0 SDK。你需要确认安装时候是否某个依赖需要python等环境，是否可以忽略
