### ISSUE TITLE
发布问卷是不是不能使用？

### ISSUE THREAD

**Issue by ZhangWren** [angular-programming/angular-questionnaire#2]
我看了下路径，路径不一样，但是我改得一样了，还是找不到，这是怎么回事啊

**Comment by yanxk888** [comment]
你好，发布功能是可用的，会生成问卷地址。不确定你这里说的路径修改具体是什么，能否贴下具体路径

**Comment by ZhangWren** [comment]
@yanxk888 你好，这是报错的

![tim 20171226170027](https://user-images.githubusercontent.com/25240164/34352626-b2d1e0f4-ea5e-11e7-80c4-49aa50b40a0e.png)

这是backend中的_db.json中的发布地址

![2](https://user-images.githubusercontent.com/25240164/34352636-bd763b86-ea5e-11e7-8c77-72ed137daba6.png)

这是questionnaire.service.ts中的发布地址

![3](https://user-images.githubusercontent.com/25240164/34352639-c2c67dda-ea5e-11e7-8614-b7af347653d4.png)


但是更改一样之后还是报错，所以不知道怎么回事，如果问的问题太简单，也请耐心解答下，谢谢

**Comment by yanxk888** [comment]
不好意思，这么晚才回复您，这里确实有点问题，书中的代码是正确的，发布调用的方法应该是 updateState，这里没有及时跟新，现已更新上去，如有其它问题，欢迎随时沟通交流
